services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkreview_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      PHP_OPCACHE_ENABLE: "0"
    depends_on:
      - db
      - redis
    networks:
      - talkreview

  nginx:
    image: nginx:1.27-alpine
    container_name: talkreview_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - talkreview

  db:
    image: mysql:8.4
    container_name: talkreview_db
    ports:
      - "33067:3306"
    environment:
      MYSQL_DATABASE: talkreview
      MYSQL_USER: talkreview
      MYSQL_PASSWORD: talkreview
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - talkreview

  redis:
    image: redis:7-alpine
    container_name: talkreview_redis
    ports:
      - "6380:6379"
    networks:
      - talkreview

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP
    networks:
      - talkreview
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - talkreview
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talkreview_reverb
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    command: sh -lc "php artisan optimize:clear && php artisan reverb:start --host=0.0.0.0 --port=6001 --debug"
    ports:
      - "6001:6001"
    depends_on:
      - db
      - redis
    networks:
      - talkreview
networks:
  talkreview:

volumes:
  db_data:
  esdata:
